### ISSUE TITLE
Data is not available from the website given

### ISSUE THREAD

**Issue by geoalgo** [facebookresearch/clutrr#14]
The page https://cs.mcgill.ca/~ksinha4/data/ referenced here https://github.com/facebookresearch/clutrr/blob/main/clutrr/main.py#L39 is not available anymore. Would it be possible to update it?

**Comment by koustuvsinha** [comment]
@geoalgo Apologies for the delayed response, somehow I missed this notification. I think this is due to a recent update I made in my personal website which erased some folders. In the meantime, you can get the data from the Google Drive link in the paper: https://drive.google.com/file/d/1SEq_e1IVCDDzsBIBhoUQ5pOVH5kxRoZF/view.
